repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
    -   id: interrogate
        args: [-vv, -i, --fail-under=50]
        verbose: true
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
# Local pre commit hook to only contril
# code quality and not block commit
- repo: local
  hooks:
   -  id: flake8
      name: flake8
      language: system
      files: .+\.py$
      entry: bash -c 'flake8 "$@" || true' --
      verbose: true
   -  id: radon
      name: radon
      language: system
      entry: bash -c 'radon cc "$@" || true' --
      verbose: true
